name: the_geolounge
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.4
  google_sign_in: ^6.1.5
  lottie: ^3.0.0
  riverpod_annotation: ^2.2.1
  google_fonts: ^6.1.0
  uuid: ^4.1.0
  flex_color_scheme: ^7.3.1
  geolocator: ^10.1.0
  device_preview: ^1.1.0
  equatable: ^2.0.5
  jiffy: ^6.2.1
  flutter_adaptive_scaffold: ^0.1.7+1
  awesome_extensions: ^2.0.11
  loader_overlay: ^4.0.0
  font_awesome_flutter: ^10.6.0
  cupertino_icons: ^1.0.2
  go_router: ^13.0.1
  slang: ^3.29.0
  slang_flutter: ^3.29.0
  supabase_flutter: ^2.3.1
  envied: ^0.5.3
  logger: ^2.0.2+1
  shared_preferences: ^2.2.2
  rxdart: ^0.27.7
  animated_tree_view: ^2.2.0
  bubble: ^1.2.1
  geocode: ^1.0.3
  url_launcher: ^6.2.5
  very_good_infinite_list: ^0.7.1
  riverpod_infinite_scroll_pagination: ^1.0.3

dev_dependencies:
  build_runner: ^2.4.6
  custom_lint: ^0.5.3
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.3.6
  riverpod_lint: ^2.0.4
  flutter_lints: ^3.0.1
  very_good_analysis: ^5.1.0
  slang_build_runner: ^3.29.0
  envied_generator: ^0.5.3
  flutter_launcher_icons: "^0.13.1"
  flutter_native_splash: ^2.3.11

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/
    - assets/i18n/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icon.png"
    background_color: "#f5fbea"
    theme_color: "#f5fbea"
  
flutter_native_splash:
  color: "#f5fbea"
  image: "assets/icon.png"